export const ExampleRows = [
  ["Amazon River", "River", "flows through", "Brazil", "Country"],
  ["Mount Everest", "Mountain", "located in", "Nepal", "Country"],
  ["Sahara", "Desert", "located in", "Africa", "Continent"],
  ["Pacific Ocean", "Ocean", "borders", "Australia", "Country"],
  ["Great Barrier Reef", "Reef", "located in", "Pacific Ocean", "Ocean"],
  ["New York City", "City", "located in", "United States", "Country"],
  ["Nile River", "River", "longest in", "Africa", "Continent"],
  ["Greenland", "Island", "is part of", "Denmark", "Country"],
  ["Himalayas", "Mountain Range", "has peak", "Mount Everest", "Mountain"],
  ["Antarctica", "Continent", "located at", "South Pole", "Geographic Pole"],
  ["Mississippi River", "River", "flows through", "United States", "Country"],
  ["Mount Kilimanjaro", "Mountain", "located in", "Tanzania", "Country"],
  ["Gobi", "Desert", "located in", "Asia", "Continent"],
  ["Atlantic Ocean", "Ocean", "borders", "United States", "Country"],
  ["Great Barrier Reef", "Reef", "part of", "Australia", "Country"],
  ["Los Angeles", "City", "located in", "United States", "Country"],
  ["Amazon River", "River", "second longest in", "South America", "Continent"],
  ["Iceland", "Island", "is part of", "Europe", "Continent"],
  ["Andes", "Mountain Range", "has peak", "Aconcagua", "Mountain"],
  [
    "Arctic",
    "Geographic Region",
    "located at",
    "North Pole",
    "Geographic Pole",
  ],
  ["Rio de Janeiro", "City", "located in", "Brazil", "Country"],
  ["Lake Victoria", "Lake", "located in", "Africa", "Continent"],
  [
    "Yellowstone National Park",
    "Park",
    "located in",
    "United States",
    "Country",
  ],
  ["Mediterranean Sea", "Sea", "borders", "Europe", "Continent"],
  ["Grand Canyon", "Canyon", "located in", "United States", "Country"],
  ["Denali", "Mountain", "highest peak in", "North America", "Continent"],
  ["The Dead Sea", "Sea", "borders", "Israel", "Country"],
  ["The Sahara", "Desert", "largest in", "Africa", "Continent"],
  ["Hawaii", "Island", "is part of", "United States", "Country"],
  ["The Alps", "Mountain Range", "has peak", "Mont Blanc", "Mountain"],
  ["The Equator", "Geographic Line", "crosses", "Africa", "Continent"],
  ["The Tropic of Cancer", "Geographic Line", "crosses", "Mexico", "Country"],
];
