# Use an official Node runtime as the parent image
FROM node:14

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY /client/package.json ./

# Copy the content of the local src directory to the working directory
COPY ./client .

# Specify the command to run on container start
CMD ["npm", "start"]
