# Start with a base image containing Python 3.8
FROM python:3.10-slim
RUN apt-get update && apt-get install -y --no-install-recommends gcc build-essential python3-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
RUN apt-get update && apt-get install -y libgdal-dev

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
ADD ./server /app

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt

# RUN uvicorn main:app
